/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_29;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.toIntExact;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chrisdaniar
 */
public class FrmRental extends javax.swing.JFrame {

    String user;
    /**
     * Creates new form FrmRental
     */
    public FrmRental(String u) {
        initComponents();
        selectdata(); 
        SetJam(); 
        SetTanggal();
        user = u;
        tfNama.setText(u);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfStruk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nol_jam = new javax.swing.JLabel();
        nol_menit = new javax.swing.JLabel();
        nol_detik = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfNopol = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        btHitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lama = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        tglKembali = new com.toedter.calendar.JDateChooser();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        label_jam = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DATA = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CariTgl = new com.toedter.calendar.JDateChooser();
        btnSearchTgl = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lama Hari");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 420, 90, 20);
        jPanel1.add(tfNama);
        tfNama.setBounds(20, 30, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Peminjam");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 150, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat Peminjam");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 70, 150, 20);
        jPanel1.add(tfStruk);
        tfStruk.setBounds(20, 190, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Struk");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Pol");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 230, 150, 20);
        jPanel1.add(nol_jam);
        nol_jam.setBounds(60, 330, 0, 0);
        jPanel1.add(nol_menit);
        nol_menit.setBounds(90, 330, 0, 0);
        jPanel1.add(nol_detik);
        nol_detik.setBounds(140, 330, 0, 0);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(20, 510, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Pinjam ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 290, 150, 20);
        jPanel1.add(tfNopol);
        tfNopol.setBounds(20, 250, 200, 30);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 90, 200, 80);

        btHitung.setText("HITUNG");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btHitung);
        btHitung.setBounds(120, 510, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 460, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Kembali");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 350, 150, 20);

        Lama.setEditable(false);
        jPanel1.add(Lama);
        Lama.setBounds(100, 420, 120, 30);

        Harga.setEditable(false);
        jPanel1.add(Harga);
        Harga.setBounds(100, 460, 120, 30);
        jPanel1.add(tglKembali);
        tglKembali.setBounds(20, 380, 200, 30);
        jPanel1.add(tglPinjam);
        tglPinjam.setBounds(20, 310, 200, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 240, 560);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HANBIN RENTAL MOTOR");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 10, 450, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 50);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setForeground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cari Nama :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 60, 90, 20);

        label_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(label_tanggal);
        label_tanggal.setBounds(80, 10, 90, 20);

        label_jam.setForeground(new java.awt.Color(255, 255, 255));
        label_jam.setText("Jam");
        jPanel3.add(label_jam);
        label_jam.setBounds(20, 30, 60, 20);

        DATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "NoStruk", "NoPol", "TanggalPinjam", "TanggalKembali", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DATA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DATAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DATA);
        if (DATA.getColumnModel().getColumnCount() > 0) {
            DATA.getColumnModel().getColumn(0).setResizable(false);
            DATA.getColumnModel().getColumn(1).setResizable(false);
            DATA.getColumnModel().getColumn(2).setResizable(false);
            DATA.getColumnModel().getColumn(3).setResizable(false);
            DATA.getColumnModel().getColumn(4).setResizable(false);
            DATA.getColumnModel().getColumn(5).setResizable(false);
            DATA.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 650, 370);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);
        btnClear.setBounds(70, 500, 90, 40);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(180, 500, 90, 40);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint);
        btnPrint.setBounds(410, 500, 90, 40);

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(290, 500, 100, 40);

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit);
        btnExit.setBounds(530, 500, 100, 40);

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch);
        btnSearch.setBounds(130, 80, 80, 30);

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        jPanel3.add(tfSearch);
        tfSearch.setBounds(20, 80, 100, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 10, 60, 20);

        jLabel12.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cari Tanggal :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(250, 60, 120, 20);
        jPanel3.add(CariTgl);
        CariTgl.setBounds(250, 80, 170, 30);

        btnSearchTgl.setText("SEARCH");
        btnSearchTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTglActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearchTgl);
        btnSearchTgl.setBounds(430, 80, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(250, 60, 700, 550);

        setBounds(0, 0, 965, 657);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat ("Daftar Transaksi Peminjaman Motor");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        try{
            DATA.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e)
                {
            System.err.format("Cannot Prnt %s%n", e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfNama.setText("");
        taAlamat.setText("");
        tfStruk.setText("");
        tfNopol.setText("");
        tglPinjam.setDate(null);
        tglKembali.setDate(null);
        Lama.setText("");
        Harga.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      selectdata();// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void selectdata() {  
        String kolom[]={"Nama","Alamat","NoStruk","NoPol","TanggalPinjam","TanggalKembali","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        String SQL = "SELECT * FROM tb_rental";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String Nama = rs.getString(1);
                String Alamat = rs.getString(2);
                String NoStruk  = rs.getString(3);
                String NoPol = rs.getString(4);
                String TanggalPinjam = rs.getString(5);
                String TanggalKembali = rs.getString(6);
                String Harga = rs.getString(7);
                
                    String data[] = {Nama, Alamat, NoStruk, NoPol, TanggalPinjam, TanggalKembali, Harga};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(FrmRental.class.getName()).log(Level.SEVERE,null, ex);
                    }
            DATA.setModel(dtm);            
    
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(tglPinjam.getDate());
        String kembali = dateFormat.format(tglKembali.getDate());
        
        if (taAlamat.getText().equals("") || Harga.getText().equals("") || pinjam.equals("") || kembali.equals("") || 
                Lama.getText().equals("") || tfNama.getText().equals("") || tfNopol.getText().equals("") || 
                tfStruk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, " Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
    } 
    else 
    {
     String SQL = "INSERT INTO tb_rental VALUES('"+tfNama.getText()+"','"+taAlamat.getText()+
             "','"+tfStruk.getText()+"','"+tfNopol.getText()+
             "','"+pinjam+"','"+kembali+"','"+Harga.getText()+"')";
     
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectdata();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE); 
            }// TODO add your handling code here:
     }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin akan menghapus data?","",JOptionPane.YES_NO_OPTION);
        int baris = DATA.getSelectedRow();
        if (confirm ==0) {
  
        if (baris != -1) {
            String Struk = DATA.getValueAt(baris, 2).toString();
            String SQL = "DELETE FROM tb_rental WHERE NoStruk='"+Struk+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status==1) {    
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        Date pinjam = tglPinjam.getDate();
        Date kembali = tglKembali.getDate();
        long waktuMulai = pinjam.getTime();
        long waktuAkhir = kembali.getTime();
        long bedaWaktu = waktuAkhir - waktuMulai;
        long bedaHari = bedaWaktu / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();

        Lama.setText(" "+bedaHari+" hari");

        int lama = toIntExact(bedaHari);
        int total = lama * 20000;
        String harga = Integer.toString(total);

        Harga.setText(harga);
    }//GEN-LAST:event_btHitungActionPerformed

    private void DATAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DATAMouseClicked
      int baris = DATA.getSelectedRow();
        if(baris != -1)
        {
            tfNama.setText(DATA.getValueAt(baris, 0).toString());
            taAlamat.setText(DATA.getValueAt(baris, 1).toString());
            tfStruk.setText(DATA.getValueAt(baris, 2).toString());
            tfNopol.setText(DATA.getValueAt(baris, 3).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try 
            {
                dateFormat = date.parse(DATA.getValueAt(baris, 4).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(FrmRental.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglPinjam.setDate(dateFormat);
            
            try 
            {
                dateFormat = date.parse(DATA.getValueAt(baris, 5).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(FrmRental.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglKembali.setDate(dateFormat);
            Harga.setText(DATA.getValueAt(baris, 6).toString());
            
            int hari = Integer.parseInt(DATA.getValueAt(baris, 6).toString()) / 20000;
            Lama.setText(" "+hari+" hari" );
        }  // TODO add your handling code here:
    }//GEN-LAST:event_DATAMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            String konString = "jdbc:mysql://localhost:3306/db_rental"; 
            Connection conn;
            conn = (com.mysql.jdbc.Connection) 
            DriverManager.getConnection(konString,"root",""); ;
            
            Statement st = conn.createStatement();
            String search = tfSearch.getText();
            ResultSet rs = st.executeQuery("SELECT * FROM tb_rental WHERE Nama like '%"+ search +"%' OR NoStruk like '%"+ search + "%'");
            DefaultTableModel dtm = (DefaultTableModel) DATA.getModel();

            dtm.setRowCount(0);
            String [] data = new String[9];
            int i = 1;

            while(rs.next())
            {
                data[0] = rs.getString("Nama");
                data[1] = rs.getString("Alamat");
                data[2] = rs.getString("NoStruk");
                data[3] = rs.getString("NoPol");
                data[4] = rs.getString("TanggalPinjam");
                data[5] = rs.getString("TanggalKembali");
                data[6] = rs.getString("Harga");
                dtm.addRow(data);
                i++;
            }
            rs.close();
            tfSearch.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
      
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btnSearchTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTglActionPerformed
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String date = dateFormat.format(CariTgl.getDate());
       String kolom[]={"Nama","Alamat","NoStruk","NoPol","TanggalPinjam","TanggalKembali","Harga"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);  
       String SQL = "SELECT * FROM tb_rental WHERE TanggalPinjam <= '"+date+"' AND TanggalKembali >= '"+date+"'";
       System.out.println(SQL);
       ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String Nama = rs.getString(1);
                String Alamat = rs.getString(2);
                String NoStruk  = rs.getString(3);
                String NoPol = rs.getString(4);
                String TanggalPinjam = rs.getString(5);
                String TanggalKembali = rs.getString(6);
                String Harga = rs.getString(7);
                
                    String data[] = {Nama, Alamat, NoStruk, NoPol, TanggalPinjam, TanggalKembali, Harga};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(FrmRental.class.getName()).log(Level.SEVERE,null, ex);
                    }
            DATA.setModel(dtm);  
    }//GEN-LAST:event_btnSearchTglActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRental(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CariTgl;
    private javax.swing.JTable DATA;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Lama;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchTgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_jam;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JLabel nol_detik;
    private javax.swing.JLabel nol_jam;
    private javax.swing.JLabel nol_menit;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNopol;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStruk;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    // End of variables declaration//GEN-END:variables

    private void SetJam() {
        ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                Date dt = new Date();
                int vh = dt.getHours();
                int vm = dt.getMinutes();
                int vs = dt.getSeconds();
                
                if (vh<=9){
                    nol_jam = "0";
                } if (vm <= 9) {
                    nol_menit = "0";
                } if (vs <= 9){
                    nol_detik = "0";
                }
               
                
                String h = nol_jam + Integer.toString(vh);
                String m = nol_menit + Integer.toString(vm);
                String s = nol_detik + Integer.toString(vs);
                label_jam.setText(h+":"+m+":"+s);
            }
    };

   new Timer(100, taskPerformer).start(); //To change body of generated methods, choose Tools | Templates.
    }

    private void SetTanggal() {
       java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyy/MM/dd");
        label_tanggal.setText(kal.format(now));//To change body of generated methods, choose Tools | Templates.
    }
}
